name: build choco package
run-name: ${{ gitea.actor }} is building appdb
on: [push]

jobs:
  build-deb:
    runs-on: automatl-net6-ubuntu2204
    if: gitea.ref == 'refs/heads/master'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: build choco
        run: |
          pushd net6 && dotnet publish -c Release -r win-x64 -t:PackChoco && popd
      - name: rename nupkg
        run: |
          mv net6/appdb.portable*.nupkg appdb.portable.nupkg
      - name: upload choco
        run: |
          choco push appdb.portable.nupkg --source https://${{ secrets.CI_USER }}:${{ secrets.CI_TOKEN }}@${{ vars.AU_GITEA_HOST }}/api/packages/audist/nuget/index.json --api-key ${{ secrets.CI_TOKEN }}
